version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: chargestationdb
      POSTGRES_USER: adilyildiz
      POSTGRES_PASSWORD: 1133
    ports:
      - "5432:5432"
    networks:
      - my-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - my-network


  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE_DOCKER:PLAINTEXT,OUTSIDE_DOCKER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE_DOCKER://kafka:9092,OUTSIDE_DOCKER://localhost:9092
      KAFKA_LISTENERS: INSIDE_DOCKER://0.0.0.0:9092,OUTSIDE_DOCKER://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE_DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - my-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - my-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - kafka
      - redis
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/chargestationdb
      SPRING_DATASOURCE_USERNAME: adilyildiz
      SPRING_DATASOURCE_PASSWORD: 1133
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
