apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - name: graphql
      port: 8083
      targetPort: {{ .Values.app.containerPort }}
      nodePort: 30080
  selector:
    app: {{ .Values.app.name }}
