name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
      - name: Run Maven Linting
        run: mvn checkstyle:check

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
      - name: Run Unit Tests
        run: mvn test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
      - name: Build JAR and Package Docker Image
        run: |
          mvn clean package -DskipTests
          docker build -t chargesquare:latest .
      - name: Push Docker Image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag chargesquare:latest ${{ secrets.DOCKER_USERNAME }}/chargesquare:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/chargesquare:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'
      - name: Set up Helm
        uses: azure/setup-helm@v3
      - name: Deploy Application to Kubernetes
        run: |
          helm upgrade chargesquare ./chargeHelm --namespace chargesquare

