name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin' # JDK dağıtımı (temurin önerilir)
      - name: Run Maven Linting
        run: mvn checkstyle:check
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt' # Specify the Java distribution (e.g., adopt, zulu)
      - name: Run Unit Tests
        run: mvn test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt' # Specify the Java distribution
      - name: Build Project
        run: mvn clean package -DskipTests

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0' # Specify kubectl version

      - name: Configure Kubernetes Cluster
        run: |
          kubectl config set-cluster chargesquare --server=https://127.0.0.1:58029
          kubectl config set-context chargesquare --cluster=chargesquare
          kubectl config use-context chargesquare

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.0' # Specify Helm version

      - name: Deploy Application to Kubernetes
        run: |
          helm upgrade --install chargesquare ./helm/chargesquare --namespace chargesquare --create-namespace
